# Google Cloud Build 설정
steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-f', 'Dockerfile.simple',
      '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/naviyam-repo/naviyam-chatbot:$BUILD_ID',
      '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/naviyam-repo/naviyam-chatbot:latest',
      '.'
    ]
  
  # Docker 이미지를 Artifact Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'asia-northeast3-docker.pkg.dev/$PROJECT_ID/naviyam-repo/naviyam-chatbot:$BUILD_ID'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'asia-northeast3-docker.pkg.dev/$PROJECT_ID/naviyam-repo/naviyam-chatbot:latest'
    ]

  # Cloud Run에 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'naviyam-chatbot',
      '--image', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/naviyam-repo/naviyam-chatbot:$BUILD_ID',
      '--platform', 'managed',
      '--region', 'asia-northeast3',
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '2Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--concurrency', '80',
      '--timeout', '300s',
      '--set-env-vars', 'PORT=8000,PYTHONUNBUFFERED=1'
    ]

# 빌드 옵션
options:
  machineType: 'E2_HIGHCPU_8'
  
# 빌드 타임아웃
timeout: '1200s'